apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2024-10-06T19:20:59Z"
  generation: 3
  labels:
    app: laser
    targetname: laser
  name: laser
  namespace: theship-vendor
  resourceVersion: "11055768"
  uid: 2fccfd98-f389-46e9-b535-4c1dbff123d1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: laser
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: laser
    spec:
      containers:
      - env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: K8S_HOST
          value: 192.168.100.11
        - name: ENCRYPTION_KEY
          value: 9105da4ec7bae4ad23224e6422dff0a3cc9b171c
        - name: SIMULATION_HOST
          value: 192.168.101.2
        image: jzeladmin2006/m321-unlimited-laser-repack
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 2018
          timeoutSeconds: 1
        name: app
        ports:
        - containerPort: 2018
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 2
          successThreshold: 1
          tcpSocket:
            port: 2018
          timeoutSeconds: 1
        resources:
          limits:
            memory: 120M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-10-06T19:20:59Z"
    lastUpdateTime: "2024-10-16T18:03:05Z"
    message: ReplicaSet "laser-b48cfdc79" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-10-22T09:25:30Z"
    lastUpdateTime: "2024-10-22T09:25:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
